CREATE TABLE FACULTY (
	Fid SMALLINT PRIMARY KEY,
	Number_Of_Students INT,
	Faculty_Name VARCHAR(100)
)

CREATE TABLE STUDENT (
	[Sid] SMALLINT PRIMARY KEY,
	SFName VARCHAR (100),
	SLName VARCHAR (100),
	Fid SMALLINT REFERENCES [FACULTY] (Fid)
		ON DELETE SET NULL
		ON UPDATE CASCADE
)

CREATE TABLE AUTHOR_CATEGORY (
	ACid SMALLINT PRIMARY KEY,
	[Time] VARCHAR (100)
)

CREATE TABLE AUTHOR (
	Aid SMALLINT PRIMARY KEY,
	AFName VARCHAR (100),
	AlName VARCHAR (100),
	ACid SMALLINT REFERENCES [AUTHOR_CATEGORY] (ACid)
		ON DELETE SET NULL
		ON UPDATE CASCADE
)

CREATE TABLE BOOK_CATEGORY (
	BCid SMALLINT PRIMARY KEY,
	CName VARCHAR (100)
)


CREATE TABLE BOOK (
	Bid SMALLINT PRIMARY KEY,
	Title VARCHAR (100),
	Release_Year DATE,
	Copies INT,
	Aid SMALLINT REFERENCES [AUTHOR] (AiD)
		ON DELETE SET NULL
		ON UPDATE CASCADE,
	BCid SMALLINT REFERENCES [BOOK_CATEGORY] (BCid)
		ON DELETE SET NULL
		ON UPDATE CASCADE
)

CREATE TABLE BORROWS (
	Borrow_Date DATE,
	Bid SMALLINT REFERENCES [BOOK] (Bid),
	[Sid] SMALLINT REFERENCES [STUDENT] ([Sid]),
	PRIMARY KEY (Bid, [Sid])
)

CREATE TABLE [RETURNS] (
	Return_Date DATE,
	Bid SMALLINT REFERENCES [BOOK] (Bid),
	[Sid] SMALLINT REFERENCES [STUDENT] ([Sid]),
	PRIMARY KEY (Bid, [Sid])
)

CREATE TABLE LIBRARIAN (
	Lid SMALLINT PRIMARY KEY,
	LFName VARCHAR (100),
	LLNAME VARCHAR (100),
	Salary INT
)

CREATE TABLE ISSUES (
	Issue_Date DATE,
	Lid SMALLINT REFERENCES [LIBRARIAN] (Lid),
	Bid SMALLINT REFERENCES [BOOK] (Bid),
	PRIMARY KEY (Lid, Bid)
)