CREATE TABLE FACULTY (
	Fid SMALLINT PRIMARY KEY IDENTITY(1,1),
	Number_Of_Students INT,
	Faculty_Name VARCHAR(100)
)

CREATE TABLE STUDENT (
	[Sid] SMALLINT PRIMARY KEY IDENTITY(1,1),
	SFName VARCHAR (100),
	SLName VARCHAR (100),
	Fid SMALLINT REFERENCES [FACULTY] (Fid)
		ON DELETE SET NULL
		ON UPDATE CASCADE
)

CREATE TABLE AUTHOR_CATEGORY (
	ACid SMALLINT PRIMARY KEY,
	[Time] VARCHAR (100)
)

CREATE TABLE AUTHOR (
	Aid SMALLINT PRIMARY KEY,
	AFName VARCHAR (100),
	AlName VARCHAR (100),
	ACid SMALLINT REFERENCES [AUTHOR_CATEGORY] (ACid)
		ON DELETE SET NULL
		ON UPDATE CASCADE
)

CREATE TABLE BOOK_CATEGORY (
	BCid SMALLINT PRIMARY KEY,
	CName VARCHAR (100)
)

CREATE TABLE BOOK (
	Bid SMALLINT PRIMARY KEY IDENTITY(1,1),
	Title VARCHAR (100),
	Release_Year DATE,
	Copies INT,
	Aid SMALLINT REFERENCES [AUTHOR] (AiD)
		ON DELETE SET NULL
		ON UPDATE CASCADE,
	BCid SMALLINT REFERENCES [BOOK_CATEGORY] (BCid)
		ON DELETE SET NULL
		ON UPDATE CASCADE
)

CREATE TABLE BORROWS (
	Borrow_Date DATE,
	Bid SMALLINT REFERENCES [BOOK] (Bid),
	[Sid] SMALLINT REFERENCES [STUDENT] ([Sid]),
	PRIMARY KEY (Bid, [Sid])
)

CREATE TABLE [RETURNS] (
	Return_Date DATE,
	Bid SMALLINT REFERENCES [BOOK] (Bid),
	[Sid] SMALLINT REFERENCES [STUDENT] ([Sid]),
	PRIMARY KEY (Bid, [Sid])
)

CREATE TABLE LIBRARIAN (
	Lid SMALLINT PRIMARY KEY IDENTITY(1,1),
	LFName VARCHAR (100),
	LLNAME VARCHAR (100),
	Salary INT
)

CREATE TABLE ISSUES (
	Issue_Date DATE,
	Lid SMALLINT REFERENCES [LIBRARIAN] (Lid),
	Bid SMALLINT REFERENCES [BOOK] (Bid),
	PRIMARY KEY (Lid, Bid)
)

CREATE TABLE [LANGUAGE] (
	Language_id SMALLINT PRIMARY KEY,
	Language_name VARCHAR (100)
)

ALTER TABLE BOOK
    ADD Language_id SMALLINT,
    FOREIGN KEY(Language_id) REFERENCES [Language](Language_id);

INSERT INTO [LANGUAGE] (Language_id, Language_name)
VALUES (1, 'romanian');

INSERT INTO [LANGUAGE] (Language_id, Language_name)
VALUES (2, 'english');

SELECT * FROM BOOK

UPDATE BOOK SET Language_id = 1 WHERE Bid = 1
UPDATE BOOK SET Language_id = 2 WHERE Bid > 1

CREATE TABLE [CHARACTER] (
	Character_id SMALLINT PRIMARY KEY,
	Character_name VARCHAR (100)
)

INSERT INTO [CHARACTER] (Character_id, Character_name)
VALUES (1, 'Hercule Poirot');

INSERT INTO [CHARACTER] (Character_id, Character_name)
VALUES (2, 'Harry Potter');

ALTER TABLE BOOK
    ADD Character_id SMALLINT,
    FOREIGN KEY(Character_id) REFERENCES [CHARACTER](Character_id);

SELECT * FROM BOOK
UPDATE BOOK SET Character_id = 1 WHERE Bid = 2 OR Bid = 3 OR Bid = 4
UPDATE BOOK SET Character_id = 2 WHERE Bid = 11 OR Bid = 12

CREATE TABLE APPEARS_IN (
	Character_id SMALLINT REFERENCES [CHARACTER] (Character_id),
	Bid SMALLINT REFERENCES [BOOK] (Bid),
	PRIMARY KEY (Character_id, Bid)
)

CREATE TABLE IS_WRITTEN_IN (
	Language_id SMALLINT REFERENCES [LANGUAGE] (Language_id),
	Bid SMALLINT REFERENCES [BOOK] (Bid),
	PRIMARY KEY (Language_id, Bid)
)