USE [UBB Library Database]
GO

-- Add/remove a primary key

CREATE PROCEDURE removePrimaryKey
AS
BEGIN
	ALTER TABLE AUTHOR
	DROP CONSTRAINT FK_Author

	ALTER TABLE AUTHOR
	DROP COLUMN ACid

	ALTER TABLE AUTHOR_CATEGORY
	DROP CONSTRAINT PK_AC
END;
GO

CREATE PROCEDURE addPrimaryKey
AS
BEGIN
	ALTER TABLE AUTHOR_CATEGORY
	ADD CONSTRAINT PK_AC PRIMARY KEY (ACid);

	ALTER TABLE AUTHOR
	ADD  ACid SMALLINT

	ALTER TABLE AUTHOR
	ADD CONSTRAINT FK_Author
	FOREIGN KEY (ACid) REFERENCES AUTHOR_CATEGORY(ACid);
END;
GO