CREATE TABLE BOOK
(
	Bid SMALLINT PRIMARY KEY,
	AName VARCHAR(50),
	Title VARCHAR(50)
)

ALTER TABLE BOOK
DROP COLUMN AuthorID

ALTER TABLE BOOK
ADD AuthorID SMALLINT

ALTER TABLE BOOK
ADD CONSTRAINT FK_BOOK FOREIGN KEY (AuthorID)
	REFERENCES dbo.AUTHOR (AuthorID)
	ON DELETE CASCADE
	ON UPDATE CASCADE

CREATE TABLE AUTHOR
(
	AuthorID SMALLINT PRIMARY KEY,
	AName VARCHAR(50)
)

CREATE TABLE [CHARACTER]
(
	Cid SMALLINT PRIMARY KEY,
	CName VARCHAR(50)
)

CREATE TABLE APPEARS_IN
(
	Aid SMALLINT,
	Bid SMALLINT REFERENCES [BOOK] (Bid),
	Cid SMALLINT REFERENCES [CHARACTER] (Cid),
	CONSTRAINT PK_APPEARSIN PRIMARY KEY (Aid, Bid, Cid)
)

INSERT INTO Tables
VALUES('Book');

INSERT INTO Tables
VALUES('Character');

INSERT INTO Tables
VALUES('Appears In');

SELECT * FROM Tables

INSERT INTO Tests
VALUES ('Test for Character');

INSERT INTO Tests
VALUES ('Test for Appears-In');

SELECT * FROM Tests

INSERT INTO Tests
VALUES ('Test for Book');

INSERT INTO TestTables
VALUES (1, 2, 2000, 5);

INSERT INTO TestTables
VALUES (2, 1, 2000, 2);

INSERT INTO TestTables
VALUES (3, 3, 7000, 10);

UPDATE TestTables SET NoOfRows = 5000 WHERE TableID = 2
UPDATE TestTables SET Position = 2 WHERE TableID = 3
UPDATE TestTables SET Position = 10 WHERE TableID = 2
UPDATE TestTables SET Position = 5 WHERE TableID = 1

SELECT * FROM TestTables

DELETE FROM BOOK
DELETE FROM AUTHOR
DELETE FROM APPEARS_IN
DELETE FROM CHARACTER


INSERT INTO [CHARACTER]
VALUES(1, 'Character-Name')

INSERT INTO AUTHOR
VALUES(1, 'Author-Name')

INSERT INTO [BOOK]
VALUES(1, 'Book-Title', 1)

INSERT INTO APPEARS_IN
VALUES(1, 1, 1)

INSERT INTO Views
VALUES ('Character View');

INSERT INTO Views
VALUES ('Book-Author View')

INSERT INTO Views
VALUES ('CharacterAppearsIn View')

SELECT * FROM Views
SELECT * FROM Tables

EXECUTE test2

SELECT * FROM TestRunViews
SELECT * FROM TestRunTables
SELECT * FROM TestRuns

SELECT * FROM [CHARACTER]

SELECT * FROM Tables


EXECUTE test1New
SELECT * FROM TestRunViews
SELECT * FROM TestRunTables
SELECT * FROM TestRuns

SELECT * FROM BOOK
SELECT * FROM AUTHOR

EXECUTE test3
SELECT * FROM TestRunViews
SELECT * FROM TestRunTables
SELECT * FROM TestRuns

SELECT * FROM APPEARS_IN
SELECT * FROM [CHARACTER]
SELECT * FROM BOOK
SELECT * FROM AUTHOR